Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
=================== RESTART: C:/Users/user/Desktop/aber.py ===================
>>> 
[DEBUG ON]
>>> 
=================== RESTART: C:/Users/user/Desktop/aber.py ===================
[DEBUG ON]
>>> regresivo(5)
54321
[DEBUG ON]
>>> 
=================== RESTART: C:/Users/user/Desktop/aber.py ===================

=================== RESTART: C:/Users/user/Desktop/aber.py ===================
[DEBUG ON]
>>> regresivo(5)
5 4 3 2 1 
[DEBUG ON]
>>> regresivo(5)
5 4 3 2 1 
[DEBUG ON]
>>> regresivo(5)
5 4 3 2 1 
[DEBUG ON]
>>> 
[DEBUG OFF]
>>> 
=================== RESTART: C:\Users\user\Desktop\aber.py ===================
>>> 
[DEBUG ON]
>>> 
=================== RESTART: C:\Users\user\Desktop\aber.py ===================
[DEBUG ON]
>>> regresivo(5)
5 4 3 2 1 
[DEBUG ON]
>>> 
=================== RESTART: C:\Users\user\Desktop\aber.py ===================
[DEBUG ON]
>>> 
[DEBUG OFF]
>>> 
=================== RESTART: C:\Users\user\Desktop\aber.py ===================
>>> fact(8)
0
>>> 
=================== RESTART: C:\Users\user\Desktop\aber.py ===================
>>> fact(8)
40320
>>> fact(4)
24
>>> 35421//10
3542
>>> 35421%10
1
>>> 3542//10
354
>>> 
=================== RESTART: C:\Users\user\Desktop\aber.py ===================
>>> prueba(35421)
35421 3542 354 35 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    prueba(35421)
  File "C:\Users\user\Desktop\aber.py", line 25, in prueba
    else: prueba(a//10)
  File "C:\Users\user\Desktop\aber.py", line 25, in prueba
    else: prueba(a//10)
  File "C:\Users\user\Desktop\aber.py", line 25, in prueba
    else: prueba(a//10)
  [Previous line repeated 974 more times]
  File "C:\Users\user\Desktop\aber.py", line 22, in prueba
    print (a, end=" ")
RecursionError: maximum recursion depth exceeded while pickling an object
>>> 
=================== RESTART: C:\Users\user\Desktop\aber.py ===================
>>> prueba(35421)
35421 3542 354 35 3 0 
>>> 
=================== RESTART: C:\Users\user\Desktop\aber.py ===================
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> suma_digitos2(34)
2
>>> suma_digitos_aux(34)
2
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> longitud_numeros2(112)
'Error'
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> longitud_numeros2(112)
'Error'
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> longitud_numeros2(112)
Traceback (most recent call last):
  File "<pyshell#17>", line 1, in <module>
    longitud_numeros2(112)
  File "E:/Noel/clase 5.py", line 56, in longitud_numeros2
    if isinstance (num, dig) and (num ==0):
NameError: name 'dig' is not defined
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> longitud_numeros2(322)
Traceback (most recent call last):
  File "<pyshell#18>", line 1, in <module>
    longitud_numeros2(322)
TypeError: longitud_numeros2() missing 1 required positional argument: 'dig'
>>> longitud_numeros2(322, 1)
Traceback (most recent call last):
  File "<pyshell#19>", line 1, in <module>
    longitud_numeros2(322, 1)
  File "E:/Noel/clase 5.py", line 56, in longitud_numeros2
    if (isinstance (num, int) and (num >=0) and (num >0)) and (insinstance(d, int) and d>=0) :
NameError: name 'insinstance' is not defined
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> longitud_numeros2(322, 1)
Traceback (most recent call last):
  File "<pyshell#20>", line 1, in <module>
    longitud_numeros2(322, 1)
  File "E:/Noel/clase 5.py", line 56, in longitud_numeros2
    if (isinstance (num, int) and (num >=0) and (num >0)) and (isinstance(d, int) and d>=0) :
NameError: name 'd' is not defined
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> longitud_numeros2(322, 1)
Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    longitud_numeros2(322, 1)
  File "E:/Noel/clase 5.py", line 58, in longitud_numeros2
    return longitud_numeros_aux2(num, dig)
UnboundLocalError: local variable 'longitud_numeros_aux2' referenced before assignment
>>> longitud_numeros2(322)
Traceback (most recent call last):
  File "<pyshell#22>", line 1, in <module>
    longitud_numeros2(322)
TypeError: longitud_numeros2() missing 1 required positional argument: 'dig'
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> longitud_numeros2(322)
Traceback (most recent call last):
  File "<pyshell#23>", line 1, in <module>
    longitud_numeros2(322)
TypeError: longitud_numeros2() missing 1 required positional argument: 'dig'
>>> longitud_numeros2(322, 2)
Traceback (most recent call last):
  File "<pyshell#24>", line 1, in <module>
    longitud_numeros2(322, 2)
  File "E:/Noel/clase 5.py", line 58, in longitud_numeros2
    return longitud_numeros_aux2(num, dig)
UnboundLocalError: local variable 'longitud_numeros_aux2' referenced before assignment
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> longitud_numeros2(322, 2)
1
>>> 
>>> longitud_numeros2(23542452542, 2)
3
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> longitud_numeros2(23542452542, 2)
4
>>> 
x= 382
>>> x%10
2
>>> x=x//10
>>> x
38
>>> x%10
8
>>> x=x//10
>>> x
3
>>> x%10
3
>>> x=x//10
>>> x%10
0
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> prueba(331231132, 3)
Traceback (most recent call last):
  File "<pyshell#39>", line 1, in <module>
    prueba(331231132, 3)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 86, in prueba_aux
    else: return prueba(num//10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 85, in prueba_aux
    return 1+prueba(num //10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 86, in prueba_aux
    else: return prueba(num//10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 86, in prueba_aux
    else: return prueba(num//10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 85, in prueba_aux
    return 1+prueba(num //10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 86, in prueba_aux
    else: return prueba(num//10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 86, in prueba_aux
    else: return prueba(num//10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 85, in prueba_aux
    return 1+prueba(num //10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 85, in prueba_aux
    return 1+prueba(num //10, dig)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
>>> prueba(331231132, 2)
Traceback (most recent call last):
  File "<pyshell#40>", line 1, in <module>
    prueba(331231132, 2)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 85, in prueba_aux
    return 1+prueba(num //10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 86, in prueba_aux
    else: return prueba(num//10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 86, in prueba_aux
    else: return prueba(num//10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 86, in prueba_aux
    else: return prueba(num//10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 86, in prueba_aux
    else: return prueba(num//10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 85, in prueba_aux
    return 1+prueba(num //10, dig)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> prueba(331231132, 2)
'Error'
>>> prueba(331231132, 3)
'Error'
>>> prueba(331231132, 8)
'Error'
>>> prueba(331231132, 10)
'Error'
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> prueba(331231132, 3)
Traceback (most recent call last):
  File "<pyshell#45>", line 1, in <module>
    prueba(331231132, 3)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 83, in prueba_aux
    return 1+prueba(num //10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 83, in prueba_aux
    return 1+prueba(num //10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 83, in prueba_aux
    return 1+prueba(num //10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 83, in prueba_aux
    return 1+prueba(num //10, dig)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> prueba(331231132, 2)
Traceback (most recent call last):
  File "<pyshell#46>", line 1, in <module>
    prueba(331231132, 2)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 83, in prueba_aux
    return 1+prueba(num //10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 83, in prueba_aux
    return 1+prueba(num //10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 83, in prueba_aux
    return 1+prueba(num //10, dig)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
>>> prueba(338, 2)
Traceback (most recent call last):
  File "<pyshell#47>", line 1, in <module>
    prueba(338, 2)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 83, in prueba_aux
    return 1+prueba(num //10, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 84, in prueba_aux
    else: return prueba(num//2, dig)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num, dig)
  File "E:/Noel/clase 5.py", line 83, in prueba_aux
    return 1+prueba(num //10, dig)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> prueba(338, 2)
'Error'
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> prueba(338, 2)¡
SyntaxError: invalid character in identifier
>>> prueba(338, 2)
'Error'
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> prueba(338)
Traceback (most recent call last):
  File "<pyshell#51>", line 1, in <module>
    prueba(338)
  File "E:/Noel/clase 5.py", line 73, in prueba
    if (isinstance (num, int) and (num >=0) and (num >0)) and (isinstance(dig, int) and dig>=0) :
NameError: name 'dig' is not defined
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> prueba(338)
Traceback (most recent call last):
  File "<pyshell#52>", line 1, in <module>
    prueba(338)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num)
  File "E:/Noel/clase 5.py", line 83, in prueba_aux
    return 1+prueba(num //10, dig)
NameError: name 'dig' is not defined
>>> prueba(338)
Traceback (most recent call last):
  File "<pyshell#53>", line 1, in <module>
    prueba(338)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num)
  File "E:/Noel/clase 5.py", line 83, in prueba_aux
    return 1+prueba(num //10, dig)
NameError: name 'dig' is not defined
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> prueba(338)
Traceback (most recent call last):
  File "<pyshell#54>", line 1, in <module>
    prueba(338)
  File "E:/Noel/clase 5.py", line 75, in prueba
    return prueba_aux(num)
  File "E:/Noel/clase 5.py", line 83, in prueba_aux
    return 1+prueba(num //10)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> impares (335)
3
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> pare_impares (214681624)
(7, 2)
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> 
======================== RESTART: E:/Noel/clase 5.py ========================
>>> 
